In [1]:
import pandas as pd
from Prediction_model import Prediction
from dataClean import cleanDataset,userCreation
from buildModel import similarityMatrixCreation

In [2]:
data_file = 'data.csv'

In [4]:
dataset = pd.read_csv(data_file,parse_dates=[['date','time']],index_col=0)
dataset = pd.DataFrame(dataset,columns=['temperature','humidity','light','voltage'])

In [5]:
dataset = cleanDataset(dataset,'temperature')

In [6]:
dataset

                            temperature  humidity  light  voltage
date_time
2004-03-31 03:38:15.757551      19.1530  38.91901  45.04  2.03397
2004-02-28 01:03:16.333930      19.3024  38.46290  45.08  2.68742
2004-02-28 01:06:16.013453      19.1652  38.80390  45.08  2.68742
2004-02-28 01:06:46.778088      19.1750  38.83790  45.08  2.69964
2004-02-28 01:08:45.992524      19.1456  38.94010  45.08  2.68742
2004-02-28 01:09:22.323858      19.1652  38.87200  45.08  2.68742
2004-02-28 01:09:46.109598      19.1652  38.80390  45.08  2.68742
2004-02-28 01:10:16.678900      19.1456  38.83790  45.08  2.69964
2004-02-28 01:10:46.250524      19.1456  38.87200  45.08  2.68742
2004-02-28 01:11:46.941288      19.1456  38.94010  45.08  2.69964
2004-02-28 01:12:46.251377      19.1358  38.90610  45.08  2.68742
2004-02-28 01:14:16.631270      19.1162  38.80390  45.08  2.69964
2004-02-28 01:14:46.569352      19.1162  38.87200  45.08  2.69964
2004-02-28 01:15:16.649556      19.1064  39.00820  45.08  2.69964
2004-02-28 01:16:16.343708      19.1064  38.87200  43.24  2.69964
2004-02-28 01:16:46.508622      19.0966  38.80390  43.24  2.69964
2004-02-28 01:17:46.427446      19.0966  38.73570  43.24  2.69964
2004-02-28 01:18:16.468248      19.0868  38.80390  43.24  2.69964
2004-02-28 01:20:16.107740      19.0672  38.90610  43.24  2.68742
2004-02-28 01:20:46.033312      19.0672  38.87200  43.24  2.69964
2004-02-28 01:21:16.648189      19.0672  38.90610  43.24  2.69964
2004-02-28 01:22:16.026390      19.0868  39.00820  43.24  2.69964
2004-02-28 01:23:16.899912      19.0182  38.73570  43.24  2.68742
2004-02-28 01:23:46.545863      19.0182  38.73570  43.24  2.69964
2004-02-28 01:24:16.176842      19.0084  38.80390  43.24  2.69964
2004-02-28 01:26:16.656972      19.0084  38.94010  43.24  2.68742
2004-02-28 01:26:46.463293      19.0084  38.94010  43.24  2.69964
2004-02-28 01:28:46.483577      18.9986  38.97420  43.24  2.68742
2004-02-28 01:29:46.102532      19.0084  38.97420  43.24  2.69964
2004-02-28 01:30:46.454955      18.9888  39.04220  43.24  2.68742
...                                 ...       ...    ...      ...
2004-02-28 02:24:46.059627      18.7242  38.80390  43.24  2.68742
2004-02-28 02:25:46.515577      18.7340  38.83790  43.24  2.69964
2004-02-28 02:26:17.231310      18.7242  38.94010  43.24  2.69964
2004-02-28 02:30:16.107116      18.7340  38.87200  43.24  2.69964
2004-02-28 02:31:16.348393      18.7242  38.94010  43.24  2.68742
2004-02-28 02:31:46.107955      18.7144  38.94010  43.24  2.68742
2004-02-28 02:34:46.698204      18.6948  38.94010  43.24  2.68742
2004-02-28 02:35:46.720846      18.6948  38.94010  43.24  2.68742
2004-02-28 02:36:16.849224      18.6850  38.87200  43.24  2.69964
2004-02-28 02:37:46.514175      18.6654  38.87200  43.24  2.68742
2004-02-28 02:40:16.927811      18.6556  38.87200  43.24  2.68742
2004-02-28 02:40:46.121260      18.6458  38.87200  43.24  2.68742
2004-02-28 02:41:16.692999      18.6360  38.87200  43.24  2.69964
2004-02-28 02:42:46.365373      18.6360  38.83790  43.24  2.68742
2004-02-28 02:43:46.923849      18.6360  38.87200  43.24  2.68742
2004-02-28 02:46:46.166591      18.6360  38.80390  43.24  2.68742
2004-02-28 02:47:46.132100      18.6164  38.87200  43.24  2.69964
2004-02-28 02:50:16.186743      18.6066  38.90610  43.24  2.68742
2004-02-28 03:02:17.064743      18.5478  38.94010  43.24  2.67532
2004-02-28 03:05:46.581160      18.5184  38.94010  43.24  2.68742
2004-02-28 03:07:46.193901      18.5086  39.00820  43.24  2.68742
2004-02-28 03:08:16.336506      18.4988  39.07630  43.24  2.68742
2004-02-28 03:08:47.118704      18.4988  39.00820  43.24  2.69964
2004-02-28 03:10:17.006142      18.4988  39.04220  43.24  2.68742
2004-02-28 03:10:46.497890      18.5086  39.04220  43.24  2.68742
2004-02-28 03:15:16.947661      18.5086  38.97420  43.24  2.68742
2004-02-28 03:19:17.102594      18.4694  38.97420  43.24  2.68742
2004-02-28 03:20:46.586630      18.4596  38.97420  43.24  2.68742
2004-02-28 03:23:46.447157      18.4400  38.94010  43.24  2.68742
2004-02-28 03:24:16.877689      18.4204  38.94010  43.24  2.68742

[98 rows x 4 columns]

In [7]:
users=userCreation(4,4,dataset)

In [8]:
users

array([[ 19.153  ,  38.91901,  45.04   , ...,  38.8379 ,  45.08   ,
          2.69964],
       [ 19.3024 ,  38.4629 ,  45.08   , ...,  38.9401 ,  45.08   ,
          2.68742],
       [ 19.1652 ,  38.8039 ,  45.08   , ...,  38.872  ,  45.08   ,
          2.68742],
       ...,
       [ 18.4988 ,  39.0422 ,  43.24   , ...,  38.9742 ,  43.24   ,
          2.68742],
       [ 18.5086 ,  39.0422 ,  43.24   , ...,  38.9742 ,  43.24   ,
          2.68742],
       [ 18.5086 ,  38.9742 ,  43.24   , ...,  38.9401 ,  43.24   ,
          2.68742]])